branches:
 except:
  - /appveyor/

language: perl
perl:
# newest without the need to download
  - "5.20"
# oldest
## XXX known to fail, see https://travis-ci.org/eserte/srezic-misc/jobs/173518047
#  - "5.8"
# newest
  - "5.24"
# and the others
  - "5.22"
  - "5.18"
# 2nd group (5 parallel jobs @ travis)
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

addons:
  apt:
    packages:
# for DB_File
      - libdb-dev

before_install:
  - git clone https://github.com/eserte/travis-helper-cpan-pm.git
  - ./travis-helper-cpan-pm/travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps
  - which cpan
# has to be patched
  - cpan Slay::Makefile
install:
  - slaymake install-prereqs-with-cpanm
script:
  - slaymake test-t
  - slaymake test-compile
