branches:
 except:
  - /appveyor/

language: perl
matrix:
  include:
# newest without the need to download
    - perl: "5.20"
# oldest
## XXX known to fail, see https://travis-ci.org/eserte/srezic-misc/jobs/173518047
#    - perl: "5.8"
# newest
    - perl: "5.24"
# actual apt-file test (with something resembling to system perl)
    - perl: "5.14"
      env: WITH_APT_FILE=1
# and the others
    - perl: "5.22"
# 2nd group (5 parallel jobs @ travis)
    - perl: "5.18"
    - perl: "5.16"
    - perl: "5.12"
    - perl: "5.10"

addons:
  apt:
    packages:
# for DB_File
      - libdb-dev
# for extended pm-to-deb tests
      - apt-file

before_install:
  - git clone https://github.com/eserte/travis-helper-cpan-pm.git
  - ./travis-helper-cpan-pm/travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps
  - which cpan
# has to be patched
  - cpan Slay::Makefile
install:
  - slaymake install-prereqs-with-cpan

before_script:
  - if [ "$WITH_APT_FILE" = "1" ]; then apt-file update; fi

script:
  - slaymake test-t
  - slaymake test-compile
