branches:
 except:
  - /appveyor/

language: perl
matrix:
  include:
# newest without the need to download
    - perl: "5.20"
      dist: trusty
# oldest
    - perl: "5.8"
      dist: trusty
# newest
    - perl: "5.30"
      dist: xenial
# actual apt-file test (with something resembling to system perl)
    - perl: "5.26"
      env: WITH_APT_FILE=1
      dist: xenial
# and the others
    - perl: "5.22"
      dist: xenial
# 2nd group (5 parallel jobs @ travis)
    - perl: "5.18"
      dist: trusty
    - perl: "5.16"
      dist: precise
    - perl: "5.12"
      dist: trusty
    - perl: "5.10"
      dist: trusty
  allow_failures:
    # Archive::Zip currently broken with 5.8: rt.cpan.org/Public/Bug/Display.html?id=130523
    - perl: "5.8"

addons:
  apt:
    packages:
# for DB_File
      - libdb-dev
# for extended pm-to-deb tests
      - apt-file
# so VCS.pm actually works
      - cvs
      - rcs

before_install:
  - git clone https://github.com/eserte/travis-helper-cpan-pm.git
  - ./travis-helper-cpan-pm/travis-helper-cpan-pm --distroprefs=https://github.com/eserte/srezic-cpan-distroprefs --enable-sysdeps
  - which cpan
# has to be patched
  - cpan Slay::Makefile
install:
  - slaymake install-prereqs-with-cpan

before_script:
  # remove possibly broken travis apt proxy, and try to refresh apt-file lists
  - if [ "$WITH_APT_FILE" = "1" ]; then sudo rm -f /etc/apt/apt.conf.d/99-travis-apt-proxy; apt-file update; fi

script:
  - slaymake test-t
  - slaymake test-compile
