#
# $Id: Makefile,v 1.1 2006/02/27 07:16:41 eserte Exp $
#

#SPIP_DIR=/usr/local/src/spip_1.5
SPIP_DIR=/usr/local/src/new.spip_1.5
SPIP_BIN=$(SPIP_DIR)/spip/bin/spip.pl
#PERL=perl
PERL=perl5.8.8

all:
	$(PERL) $(SPIP_BIN)
