#!/bin/sh

set -e

CPAN_SMOKE_MODULES=~eserte/work/srezic-misc/scripts/cpan_smoke_modules
ALL_RECENT_FILE=/tmp/cpansand-RECENT.yml

cat <<EOF
Remember to run

    cd ~/trash/RECENT && wget ftp://ftp.funet.fi/pub/CPAN/authors/id/RECENT-2d.yaml && chmod o+r RECENT-2d*

first as eserte.
Continue?
EOF
read yn

perl -MList::MoreUtils=uniq -MYAML::Syck=LoadFile,Dump -e 'for (@ARGV) { push @x, @{ LoadFile($_) } } @x = grep { $_->{path} eq $last ? 0 : do { $last = $_->{path}; 1 } } sort { $b->{epoch} <=> $a->{epoch} } @x; print Dump(\@x) ' ~eserte/trash/RECENT/RECENT-2d*.yaml* > $ALL_RECENT_FILE

xterm -geometry +0+0   -e $CPAN_SMOKE_MODULES -warntimeout 0 -recent -recenturl file:$ALL_RECENT_FILE -batch -c -wait -pv 5.10.0 &
xterm -geometry -0+0   -e $CPAN_SMOKE_MODULES -warntimeout 0 -recent -recenturl file:$ALL_RECENT_FILE -batch -c -wait -pv 5.8.8 -r &
xterm -geometry +0+338 -e $CPAN_SMOKE_MODULES -warntimeout 0 -recent -recenturl file:$ALL_RECENT_FILE -batch -c -wait -pv 5.6.2 &
xterm -geometry -0-338 -e $CPAN_SMOKE_MODULES -warntimeout 0 -recent -recenturl file:$ALL_RECENT_FILE -batch -c -wait -pv 5.00505 -r &
xterm -geometry +0-0   -e $CPAN_SMOKE_MODULES -warntimeout 0 -recent -recenturl file:$ALL_RECENT_FILE -batch -c -wait -pv 5.10.0t -r &

# Wait until all xterm are settled
sleep 3
cpansandtty=""
for tty in /dev/tty[pq]*
do
  user=`stat -f %Su $tty`
  lsof=`lsof $tty | wc -l`
  if [ $lsof -gt 0 ]
  then
      case $user in
	  cpansand) cpansandtty="$cpansandtty $tty" ;;
      esac
  fi
done
~eserte/work/srezic-misc/scripts/idletermchecker -t 60 -t2 120 -tk $cpansandtty &

tail -f ~/.cpanreporter/reports-sent.db
