#!/bin/sh

# Untested!

doupdate=1
only=
also_failed=0
today_grep=cat

args=`getopt Uo:ftd: $*`
if [ $? -ne 0 ]
then
    echo 'Usage: $0 [-U] [-o perlversion] [-f] [-t] [-d yyyy-mm-dd]'
    exit 2
fi
set -- $args
for i do
    case "$i" in
	-U)
	    doupdate=0
	    shift
	    ;;
	-o)
	    only="$2"
	    shift
	    shift
	    ;;
	-f)
	    also_failed=1
	    shift
	    ;;
	-t)
	    today=`date +%Y-%m-%d`
	    today_grep="grep $today"
	    shift
	    ;;
	-d)
	    today="$2"
	    today_grep="grep $today"
	    shift
	    shift
	    ;;
	--)
	    shift
	    break
	    ;;
    esac
done

get_untested() {
    local perlver=$1
    grep -v '^[#\?]' ~/var/tested-cpan-$perlver | grep -v ' tested' | $today_grep | sort -r | head -1000 | awk '{print $2}'
}

get_failed_and_untested() {
    local perlver=$1
    grep -v '^[#\?]' ~/var/tested-cpan-$perlver | grep -v ' tested .*PASS' | $today_grep | sort -r | head -1000 | awk '{print $2}'
}

get_distros() {
    local perlver=$1
    case $also_failed in
	1)
	    get_failed_and_untested $perlver
	    ;;
	*)
	    get_untested $perlver
	    ;;
    esac
}

set -e

PATH=$PATH:~eserte/work/srezic-misc/scripts:~eserte/devel

[ -r /home/e/eserte/.cpan/CPAN/MyConfig.pm ] || (echo "CPAN config is not readable!"; exit 1)

CPAN_SMOKE_MODULES=cpan_smoke_modules
CPAN_SMOKE_MODULE_ARGS="-nosqlite -batch -wait "
XTERM_ARGS="-xrm *Desk:3"
case "$today" in
    2*)
	XTERM_ARGS="-xrm *Desk:2"
	;;
esac

case $doupdate in
    1)
	perl -MCPAN -e 'CPAN::HandleConfig->load; $CPAN::Config->{use_sqlite}=1; CPAN::Shell->reload("index")'
	update-allcpanpackages
	;;
esac

sleep=0

## Sends FAIL reports without asking with CPAN::Reporter 1.11
## Again enabled with CPAN::Reporter 1.13, have to check for problems...
if [ "$only" = "" -o "$only" = "5.10.0" ]
then
    LAST_UNTESTED_DISTROS_5_10_0="`get_distros 5.10.0`"
    echo $LAST_UNTESTED_DISTROS_5_10_0  > ~/.cpan_test_distros_5_10_0
    (sleep $sleep; xterm $XTERM_ARGS -geometry +0+0   -e $CPAN_SMOKE_MODULES $CPAN_SMOKE_MODULE_ARGS -rr -pv 5.10.0  $LAST_UNTESTED_DISTROS_5_10_0) &
    sleep=`expr $sleep + 3`
fi

# Note that I don't test ports uploaded 2007 - 2008-02-29, because these
# were already tested by the previous perl port with "6.2" in the osvers
if [ "$only" = "" -o "$only" = "5.8.8" ]
then
    LAST_UNTESTED_DISTROS_5_8_8="`get_distros 5.8.8`"
    echo $LAST_UNTESTED_DISTROS_5_8_8   > ~/.cpan_test_distros_5_8_8
    (sleep $sleep;  xterm $XTERM_ARGS -geometry -0+0   -e $CPAN_SMOKE_MODULES $CPAN_SMOKE_MODULE_ARGS   -pv 5.8.8   $LAST_UNTESTED_DISTROS_5_8_8  )&
    sleep=`expr $sleep + 3`
fi

if [ "$only" = "" -o "$only" = "5.6.2" ]
then
    LAST_UNTESTED_DISTROS_5_6_2="`get_distros 5.6.2`"
    echo $LAST_UNTESTED_DISTROS_5_6_2   > ~/.cpan_test_distros_5_6_2
    (sleep $sleep; xterm $XTERM_ARGS -geometry +0+338 -e $CPAN_SMOKE_MODULES $CPAN_SMOKE_MODULE_ARGS -rr -pv 5.6.2   $LAST_UNTESTED_DISTROS_5_6_2  )&
    sleep=`expr $sleep + 3`
fi

## Suspended 5.00505 testing, because CPAN::Reporter 1.11 does not obey the prereq specs
## Again enabled with CPAN::Reporter 1.13, have to check for problems...
## Still same problems (sample: WPA-CLI)
#if [ "$only" = "" -o "$only" = "5.00505" ]
#then
#    LAST_UNTESTED_DISTROS_5_00505="`get_distros 5.00505`"
#    echo $LAST_UNTESTED_DISTROS_5_00505 > ~/.cpan_test_distros_5_00505
#    (sleep $sleep; xterm $XTERM_ARGS -geometry -0-0 -e $CPAN_SMOKE_MODULES $CPAN_SMOKE_MODULE_ARGS   -pv 5.00505 $LAST_UNTESTED_DISTROS_5_00505)&
#    sleep=`expr $sleep + 3`
#fi

if [ "$only" = "" -o "$only" = "5.8.8t" ]
then
    LAST_UNTESTED_DISTROS_5_8_8t="`get_distros 5.8.8t`"
    echo $LAST_UNTESTED_DISTROS_5_8_8t > ~/.cpan_test_distros_5_8_8t
    (sleep $sleep; xterm $XTERM_ARGS -geometry -0+338   -e $CPAN_SMOKE_MODULES $CPAN_SMOKE_MODULE_ARGS   -pv 5.8.8t $LAST_UNTESTED_DISTROS_5_8_8t)&
    sleep=`expr $sleep + 3`
fi

if [ "$only" = "" -o "$only" = "5.10.0t" ]
then
    LAST_UNTESTED_DISTROS_5_10_0t="`get_distros 5.10.0t`"
    echo $LAST_UNTESTED_DISTROS_5_10_0t > ~/.cpan_test_distros_5_10_0t
    (sleep $sleep; xterm $XTERM_ARGS -geometry +0-0   -e $CPAN_SMOKE_MODULES $CPAN_SMOKE_MODULE_ARGS   -pv 5.10.0t $LAST_UNTESTED_DISTROS_5_10_0t)&
    sleep=`expr $sleep + 3`
fi

## Wait until all xterm are settled
#sleep $sleep
#sleep 3
#cpansandtty=""
#for tty in /dev/tty[pq]*
#do
#  user=`stat -f %Su $tty`
#  lsof=`lsof $tty | wc -l`
#  if [ $lsof -gt 0 ]
#  then
#      case $user in
#	  cpansand) cpansandtty="$cpansandtty $tty" ;;
#      esac
#  fi
#done
#idletermchecker -t 60 -t2 120 -tk $cpansandtty &

tail -f ~/.cpanreporter/reports-sent.db
