#!/bin/sh

# Untested!

set -e

CPAN_SMOKE_MODULES=~eserte/work/srezic-misc/scripts/cpan_smoke_modules

~/devel/update-allcpanpackages

for perl in 5.10.0 5.8.8 5.6.2 5.00505 5.10.0t; do
    varname=`echo $perl | sed -e 's/\./_/g'`
    LAST_UNTESTED_DISTROS_$varname=`grep -v '^\?' ~eserte/var/tested-cpan-$perl | sort -r | head -200 | awk '{print $2}'`
done

xterm -geometry +0+0   -e $CPAN_SMOKE_MODULES -r -warntimeout 0 -batch -c -wait -pv 5.10.0  $LAST_UNTESTED_DISTROS_5_10_0  &
xterm -geometry -0+0   -e $CPAN_SMOKE_MODULES    -warntimeout 0 -batch -c -wait -pv 5.8.8   $LAST_UNTESTED_DISTROS_5_8_8   &
xterm -geometry +0+338 -e $CPAN_SMOKE_MODULES -r -warntimeout 0 -batch -c -wait -pv 5.6.2   $LAST_UNTESTED_DISTROS_5_6_2   &
xterm -geometry -0-338 -e $CPAN_SMOKE_MODULES    -warntimeout 0 -batch -c -wait -pv 5.00505 $LAST_UNTESTED_DISTROS_5_00505 &
xterm -geometry +0-0   -e $CPAN_SMOKE_MODULES    -warntimeout 0 -batch -c -wait -pv 5.10.0t $LAST_UNTESTED_DISTROS_5_10_0t &

# Wait until all xterm are settled
sleep 3
cpansandtty=""
for tty in /dev/tty[pq]*
do
  user=`stat -f %Su $tty`
  lsof=`lsof $tty | wc -l`
  if [ $lsof -gt 0 ]
  then
      case $user in
	  cpansand) cpansandtty="$cpansandtty $tty" ;;
      esac
  fi
done
~eserte/work/srezic-misc/scripts/idletermchecker -t 60 -t2 120 -tk $cpansandtty &

tail -f ~/.cpanreporter/reports-sent.db
