#!/usr/bin/perl -w
# -*- perl -*-

#
# $Id: cpan-recent-uploads,v 1.1 2008/04/09 20:23:02 eserte Exp $
# Author: Slaven Rezic
#
# Copyright (C) 2008 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: slaven@rezic.de
# WWW:  http://www.rezic.de/eserte/
#

use strict;
use Net::NNTP;

my $n = shift || 100;

my $nntp_host = "nntp.perl.org";
my $nntp = Net::NNTP->new($nntp_host);
die "Can't connect to $nntp_host" if !$nntp;
my(undef,undef,$last) = $nntp->group("perl.cpan.uploads");
my $first = $last - $n;
$first = 1 if $first < 1;
my $res = $nntp->xhdr("Subject", $first."-".$last);
my @res = grep { s/^CPAN Upload:\s*// } map { $res->{$_} } sort { $b <=> $a } keys %$res;
print join("\n", @res), "\n";

__END__
