#!/usr/bin/perl

use strict;
use Getopt::Long;

my $do_this_month = 1;
my $do_last_month = 1;
my $do_recent;

my $do_maintperl;
my $do_all;

my $skip_update;

GetOptions("maintperl" => \$do_maintperl,
	   "all"       => \$do_all,
	   "this!"     => \$do_this_month,
	   "last!"     => \$do_last_month,
	   "recent"    => \$do_recent,
	   "skip-update" => \$skip_update,
	  )
    or die "usage?";

if (!$do_maintperl && !$do_all) {
    die "Please specify either -maintperl or -all";
}

if ($do_maintperl) {
    (getpwuid($<))[0] eq 'cpansand'
	or die "Works only for cpansand!";
    unless ($skip_update) {
	my @cmd = "/home/e/eserte/devel/update-allcpanpackages";
	warn "@cmd...\n";
	if (system(@cmd) != 0) {
	    die "update failed";
	}
    }

    my(undef,undef,undef,undef,$m,$y) = localtime;
    $m++;
    $y+=1900;
    my $this_month = sprintf "%04d-%02d-", $y, $m;
    $m--;
    if ($m < 1) {
	$m = 12;
	$y--;
    }
    my $last_month = sprintf "%04d-%02d-", $y, $m;

    my $cmd = <<'EOF';
env PERL_BATCH=yes PERL_CPAN_REPORTER_DIR=$HOME/.cpanreporter/set3 ~eserte/work/srezic-misc/scripts/cpan_smoke_modules -install -nodestroyperl -skiptested -perl /usr/perl5.8.8@34559/bin/perl `sort -r ~cpansand/var/tested-cpan-FreeBSD-5.8.8@34559 | grep -v '^\?' | egrep '(untested|not the latest version)' | egrep '^__DATE__' | sort -r | perl -nale 'print $F[1]'`
EOF
    $cmd =~ s{__DATE__}{($this_month|$last_month)};
    warn "Running '$cmd'...\n";
    system $cmd;
    if ($? != 0) {
	die "Command failed with $?";
    }
} elsif (0 && $do_maintperl) { # old
    unless ($skip_update) {
	my @cmd = "/home/e/eserte/devel/update-allcpanpackages";
	warn "@cmd...\n";
	if (system(@cmd) != 0) {
	    die "update failed";
	}
    }
#     if (!$do_this_month && !$do_last_month) {
# 	$do_this_month = 1;
#     }
    my(undef,undef,undef,undef,$m,$y) = localtime;
    $m++;
    $y+=1900;
    my $this_month = sprintf "%04d-%02d-", $y, $m;
    $m--;
    if ($m < 1) {
	$m = 12;
	$y--;
    }
    my $last_month = sprintf "%04d-%02d-", $y, $m;
    my @cmd = ("/home/e/eserte/work/srezic-misc/scripts/cpan_smoke_modules",
	       "-skiptested", "-install",
	       "-perl", '/usr/perl5.8.8@34559/bin/perl'
	      );
    my @dists;
    {
	open my $fh, "$ENV{HOME}/var/tested-cpan-FreeBSD-5.8.8"
	    or die $!;
	while(<$fh>) {
	    chomp;
	    my @F = split;
	    push @dists, $F[1]
		if (($do_this_month && $F[0] =~ m{^\Q$this_month}) ||
		    ($do_last_month && $F[0] =~ m{^\Q$last_month}));
	}
    }
    if (!@dists) {
	warn "No distributions to test...\n";
	exit;
    }
    push @cmd, @dists;
    warn "@cmd...\n";
    if (system(@cmd) != 0) {
	die "Failed while running command";
    }
} else {
    my @dists;
    {
	open my $fh, "-|", "/home/e/eserte/work/srezic-misc/scripts/cpan_recent_uploads"
	    or die "While running cpan_recent_uploads: $!";
	while(<$fh>) {
	    chomp;
	    push @dists, $_;
	}
    }
    my @cmd = ("/home/e/eserte/work/srezic-misc/scripts/cpan_smoke_modules", "-skiptested", "-bleededge", @dists);
    warn "@cmd...\n";
    if (system(@cmd) != 0) {
	die "Failure while running command\n";
    }
}
