#!/usr/bin/perl -w
# -*- perl -*-

#
# Author: Slaven Rezic
#
# Copyright (C) 2017 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: slaven@rezic.de
# WWW:  http://www.rezic.de/eserte/
#

use strict;
use File::Temp ();

my $url = shift
    or die "Please specify URL or something else\n";

my $temp = File::Temp->new(SUFFIX => '.png');

if (eval { require Imager::QRCode; 1 }) {
    my $qrcode = Imager::QRCode->new(
				     casesensitive => 1,
				    );
    my $img = $qrcode->plot($url);
    $img->write(file => "$temp")
	or die $img->errstr;
} else {
    require GD::Barcode::QRCode;

    print $temp GD::Barcode::QRcode->new($url,
					 { Ecc => 'L', Version=>12, ModuleSize => 4},
					)->plot->png;
    close $temp
	or die $!;
}

system 'eog', $temp;

__END__
