#!/usr/bin/perl -w
# -*- perl -*-

#
# Author: Slaven Rezic
#
# Copyright (C) 2017,2020 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: slaven@rezic.de
# WWW:  http://www.rezic.de/eserte/
#

use strict;
use File::Temp qw(tempdir);

my $url = shift
    or die "Please specify URL or something else\n";

my $tempdir = tempdir("qrcode_XXXXXXXX", TMPDIR =>1, CLEANUP => 1);
my $tempfile = "$tempdir/qrcode.png";
open my $tempfh, ">", $tempfile or die $!;

if (eval { require Imager::QRCode; 1 }) {
    my $qrcode = Imager::QRCode->new(
				     casesensitive => 1,
				    );
    my $img = $qrcode->plot($url);
    $img->write(file => $tempfile)
	or die $img->errstr;
} else {
    require GD;
    require GD::Barcode::QRcode;

    print $tempfh GD::Barcode::QRcode->new($url,
					   { Ecc => 'L', Version=>12, ModuleSize => 4},
					  )->plot->png;
    close $tempfh
	or die $!;
}

if ($^O eq 'darwin') {
    system 'open', '-W', $tempfile;
} else {
    system 'eog', '--new-instance', $tempfile;
}

__END__
