#!/usr/bin/env perl
use strict;
use warnings;
use POSIX qw(strftime);
use File::Spec;
use Time::HiRes qw(time);

my $tkm_ret;
my $lastcmd;
my $starttime;
my $endtime;

if (@ARGV) {
    $lastcmd = join(" ", map { m{\s} ? "'$_'" : $_ } @ARGV);
    $starttime = time();
    system(@ARGV);
    $tkm_ret = $? >> 8;
} else {
    $lastcmd = "last command";
}

if (length($lastcmd) > 164) {
    $lastcmd = substr($lastcmd, 0, 80) . "..." . substr($lastcmd, -80);
}

$endtime = time();

my $bg = "yellow";
my $fg = "black";
if (defined $tkm_ret) {
    $bg = ($tkm_ret == 0) ? "green4" : "red";
    $fg = "white";
}

my $found;
my $tkmessage_path;
for my $p (split /:/, $ENV{PATH}) {
    my $tk_candidate = File::Spec->catfile($p, "tkmessage");
    if (-x $tk_candidate) {
        $found = "tkmessage";
        $tkmessage_path = $tk_candidate;
        last;
    }
    my $x_candidate = File::Spec->catfile($p, "xmessage");
    if (-x $x_candidate && !defined $found) {
        $found = "xmessage";
    }
}

my $timeinfo;
my $st_str = defined $starttime ? strftime("%FT%T", localtime($starttime)) : undef;
my $et_str = strftime("%FT%T", localtime($endtime));

if (defined $starttime) {
    my $dur = sprintf("%.3f", $endtime - $starttime);
    $timeinfo = "<$st_str - $et_str> <${dur}s>";
} else {
    $timeinfo = "<$et_str>";
}

my $ret_str = defined $tkm_ret ? "<$tkm_ret> " : "";

if ($found && $found eq "tkmessage") {
    my $perl = "perl";
    for my $p (split /:/, $ENV{PATH}) {
        if (-x File::Spec->catfile($p, "pistachio-perl")) {
            $perl = "pistachio-perl";
            last;
        }
    }
    my $msg = "$lastcmd\n$ret_str$timeinfo";
    if (fork() == 0) {
        exec($perl, $tkmessage_path, "-center", "-bg", $bg, "-fg", $fg, "-title", "Last command", "-font", "Courier 14 bold", $msg);
        die "exec failed: $!";
    }
} elsif ($found && $found eq "xmessage") {
    my $msg = "$ret_str$timeinfo $lastcmd";
    if (fork() == 0) {
        exec("xmessage", "-center", "-bg", $bg, "-fg", $fg, "-title", "Last command", "-font", "-adobe-courier-medium-o-normal--14-*", $msg);
        die "exec failed: $!";
    }
} else {
    print "$ret_str$timeinfo $lastcmd\n";
}

exit($tkm_ret // 0);
