#!/usr/bin/perl -w
# -*- perl -*-

#
# $Id: xmlgrep,v 1.1 2007/07/08 18:07:20 eserte Exp $
# Author: Slaven Rezic
#
# Copyright (C) 2006 Slaven Rezic. All rights reserved.
# This program is free software; you can redistribute it and/or
# modify it under the same terms as Perl itself.
#
# Mail: slaven@rezic.de
# WWW:  http://www.rezic.de/eserte/
#

use strict;
use Getopt::Long;
use XML::LibXML;

my $p = XML::LibXML->new;

my %opt;
GetOptions(\%opt, "as-xml!")
    or die "usage!";

my $xpath = shift @ARGV;
my @files = @ARGV;

if (@files) {
    for my $file (@files) {
	open my $fh, $file
	    or warn "Can't open $file: $!", next;
	xmlgrep($fh);
    }
} else {
    xmlgrep(\*STDIN);
}

sub xmlgrep {
    my($fh) = @_;
    my $doc = $p->parse_fh($fh)
	or return;
    my $root = $doc->documentElement;
    for my $node ($root->findnodes($xpath)) {
	if ($opt{"as-xml"}) {
	    print $node->toString, "\n";
	} else {
	    print $node->to_literal, "\n";
	}
    }
}

__END__
