#
# $Id: Makefile,v 1.1 2005/08/10 22:59:43 eserte Exp $
#

all:

dist:
	cd ..; tar cfvz /tmp/tkgnuplot.tar.gz \
		tkgnuplot/tkgnuplot.html \
		tkgnuplot/tkgnuplot1 \
		tkgnuplot/tkgnuplot2 \
		tkgnuplot/tkgnuplot1.gif \
		tkgnuplot/tkgnuplot2.gif
	uuencode /tmp/tkgnuplot.tar.gz tkgnuplot.tar.gz > /tmp/tkgnuplot.uu

